from django.urls import path, include
# from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user/addresses', views.addresses, name='addresses'),
    path('ajax/user/addresses/new', views.ajaxNewAddress, name='ajaxNewAddress'),

    path('import/exchange', views.importExchangeTrades, name='importExchange'),
    path('import/transactions', views.importTransactions, name='importTransactions'),
    path('import/manageCoins/', views.manageCoins, name='manageCoins'),
    path('import/tokens', views.importTokens, name='importTokens'),
    path('ajax/tokens/new', views.ajaxNewToken, name='ajaxNewToken'),
    path('ajax/tokens/notSpam/<tokenId>', views.ajaxTokenNotSpam, name='ajaxTokenNotSpam'),
    path('import/testAutocomplete', views.testAutocomplete, name='testAutocomplete'),
    path('ajax/import/transactions', views.ajaxImportTransactions, name='ajaxImportTransactions'),
    path('ajax/import/transaction', views.ajaxImportTx, name='ajaxImportTx'),
    path('ajax/import/tokenTransfer', views.ajaxImportTtx, name='ajaxImportTtx'),
    path('ajax/import/incomingTransactions', views.ajaxImportIncomingTransactions, name='ajaxImportIncomingTransactions'),
    path('ajax/import/incomingInternalTransactions', views.ajaxImportIncomingInternal, name='ajaxImportIncomingInternal'),
    path('ajax/import/tokenTransfer', views.ajaxImportTokenTransfers, name='ajaxImportTokenTransfers'),
    path('ajax/import/transactions/tos', views.ajaxImportTxTos, name='ajaxImportTxTos'),
    path('ajax/import/transactions/fees', views.ajaxImportTxFees, name='ajaxImportTxFees'),
    path('ajax/import/transactions/values', views.ajaxImportTxValues, name='ajaxImportTxValues'),
    path('ajax/import/transactions/fees/spends', views.ajaxTxFeeSpends, name='ajaxTxFeeSpends'),
    path('ajax/import/transactions/fees/poll', views.ajaxPollTxFees, name='ajaxPollTxFees'),

    path('ajax/process/transactions/approvals', views.ajaxProcessApprovals, name='ajaxProcessApprovals'),
    path('ajax/process/transactions/dexTrades', views.ajaxProcessDexTrades, name='ajaxProcessDexTrades'),
    path('ajax/process/transactions/dexTrades/oops', views.ajaxProcessDexOops, name='ajaxProcessDexOops'),
    path('ajax/process/transactions/dexTrades/create', views.ajaxCreateDexTrade, name='ajaxCreateDexTrade'),
    path('ajax/process/transactions/depositsAndSends', views.ajaxProcessDepositsAndSends, name='ajaxProcessDepositsAndSends'),
    path('ajax/process/transactions/<txId>/dexTrade', views.ajaxProcessDexTrade, name='ajaxProcessDexTrade'),
    path('ajax/process/transactions/<txId>/nearestIncoming', views.ajaxNearestIncomingTransfer, name='ajaxNearestIncomingTransfer'),
    path('ajax/process/transactions/<txId>/<ttxId>/cowSwap', views.ajaxProcessCoWSwap, name='ajaxProcessCoWSwap'),
    path('ajax/process/transactions/<txId>/harvest', views.ajaxProcessHarvest, name='ajaxProcessHarvest'),
    path('ajax/process/transactions/<txId>/bridgeSend', views.ajaxProcessBridgeSend, name='ajaxProcessBridgeSend'),
    path('ajax/process/transactions/<txId>/vaultDeposit', views.ajaxProcessVaultDeposit, name='ajaxProcessVaultDeposit'),
    path('ajax/process/transactions/<txId>/vaultIncome', views.ajaxProcessVaultIncome, name='ajaxProcessVaultIncome'),
    path('ajax/process/transactions/<txId>/vaultDepositAndIncome', views.ajaxProcessVaultDepositAndIncome, name='ajaxProcessVaultDepositAndIncome'),
    path('ajax/process/transactions/<txId>/vaultWithdrawal', views.ajaxProcessVaultWithdrawal, name='ajaxProcessVaultWithdrawal'),
    path('ajax/withdrawals/<wId>/received', views.ajaxAddWithdrawalReceived, name='ajaxAddWithdrawalReceived'),
    path('ajax/process/transactions/<txId>/vaultRestake', views.ajaxProcessVaultRestake, name='ajaxProcessVaultRestake'),
    path('ajax/process/transactions/<txId>/vaultMigrate', views.ajaxProcessVaultMigrate, name='ajaxProcessVaultMigrate'),
    path('ajax/process/transactions/<txId>/vault/withdrawAndTrade', views.ajaxProcessVaultWithdrawAndTrade, name='ajaxProcessVaultWithdrawAndTrade'),
    path('ajax/process/transactions/income', views.ajaxProcessIncome, name='ajaxProcessIncome'),
    path('ajax/process/transactions/initAirdrop', views.ajaxProcessInitialAirdrop, name='ajaxProcessInitialAirdrop'),
    path('ajax/process/transactions/<txId>/spend', views.ajaxProcessSpend, name='ajaxProcessSpend'),
    path('ajax/process/transactions/<txId>/asFailed', views.ajaxProcessFailedTx, name='ajaxProcessFailedTx'),
    path('ajax/process/transactions/<txId>/asProcessed', views.ajaxMarkAsProcessed, name='ajaxMarkAsProcessed'),
    path('ajax/process/transactions/<txId>/matching', views.ajaxFindMatchingTxs, name='ajaxFindMatchingTxs'),

    path('reports/coin_summary', views.coin_summary, name='coin_summary'),
    path('reports/buys', views.buysReport, name='buysReport'),
    path('reports/transactions', views.transactionsReport, name='transactionsReport'),
    path('reports/transactions/<txId>', views.viewTransaction, name='viewTransaction'),
    path('reports/transactions/<txId>/nextUnprocessed/<direction>', views.nextUnprocessed, name='nextUnprocessed'),
    path('reports/sales', views.salesReport, name='salesReport'),
    path('reports/spends', views.spendsReport, name='spendsReport'),
    path('reports/bridges', views.bridgesReport, name='bridgesReport'),
    path('reports/withdrawals', views.withdrawalsReport, name='withdrawalsReport'),
    path('reports/tokens', views.tokensReport, name='tokensReport'),
    path('reports/holdings', views.holdingsReport, name='holdingsReport'),
    path('reports/vaults', views.vaultsReport, name='vaultsReport'),
    path('reports/cgt', views.cgtReport, name='cgtReport'),
    path('reports/aud', views.audReport, name='audReport'),
    path('reports/income', views.incomeReport, name='incomeReport'),

    path('tax/processing', views.taxProcessing, name='taxProcessing'),
    path('ajax/tax/processing/getCGTEvents/<year>/', views.ajaxGetCGTEvents, name='ajaxGetCGTEvents'),
    path('ajax/tax/processing/calcCGT/<year>/<applyLossesAndDiscount>/', views.ajaxCalculateCGT, name='ajaxCalculateCGT'),
    path('tax/getCSV/<year>/', views.taxReportCsv, name='taxReportCsv'),
    path('tax/getCSV/<year>/headlines/', views.taxReportCsvHeadlines, name='taxReportCsvHeadlines'),
    path('tax/getFYReportCSV/<year>/', views.financialYearSummary, name='FYReportCsv'),
    path('tax/transactionScreenshots/<int:year>/', views.TransactionScreenshots, name='TransactionScreenshots'),
    path('ajax/tax/testScreenshot/<txId>/', views.ajaxTestScreenshot, name='ajaxTestScreenshot'),

    path('ajax/coins/search/', views.ajaxSearchCoins, name='ajaxSearchCoins'),
    path('ajax/coins/search/ofUser/', views.ajaxSearchCoinsOfUser, name='ajaxSearchCoinsOfUser'),
    
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)