# Generated by Django 4.1.2 on 2023-08-17 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', gnosis.eth.django.models.EthereumAddressV2Field()),
            ],
            options={
                'db_table': 'addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', gnosis.eth.django.models.Uint256Field()),
                ('unitPrice', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('fee', gnosis.eth.django.models.Uint256Field(blank=True, null=True)),
                ('feeAUD', models.FloatField()),
            ],
            options={
                'db_table': 'buys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('endpoint', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'chains',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('coingecko_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'coins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', gnosis.eth.django.models.Uint256Field()),
                ('unitPrice', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('fee', gnosis.eth.django.models.Uint256Field(blank=True, null=True)),
                ('feeAUD', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('feeCoin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_fee', to='taxApp.coin')),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cryptoTaxUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', gnosis.eth.django.models.Uint256Field(blank=True, null=True)),
                ('txHash', gnosis.eth.django.models.HexV2Field()),
                ('date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.address')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.chain')),
                ('feeCoin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', gnosis.eth.django.models.EthereumAddressV2Field(max_length=128)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.chain')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
            ],
            options={
                'db_table': 'tokens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxApp.buy')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxApp.sale')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction')),
            ],
            options={
                'db_table': 'swaps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', gnosis.eth.django.models.Uint256Field()),
                ('unitPrice', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
            options={
                'db_table': 'spends',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', gnosis.eth.django.models.Uint256Field()),
                ('unitPrice', models.FloatField()),
                ('date', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
            options={
                'db_table': 'incomes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', gnosis.eth.django.models.Uint256Field()),
                ('unitPrice', models.FloatField()),
                ('date', models.DateTimeField()),
                ('remaining', gnosis.eth.django.models.Uint256Field()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
            options={
                'db_table': 'costbases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CGTEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', gnosis.eth.django.models.Uint256Field()),
                ('unitPrice', models.FloatField()),
                ('date', models.DateTimeField()),
                ('consumed', gnosis.eth.django.models.Uint256Field()),
                ('discounted', models.BooleanField()),
                ('gain', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('costBasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.costbasis')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.sale')),
                ('spend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.spend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin'),
        ),
        migrations.AddField(
            model_name='buy',
            name='feeCoin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_fee', to='taxApp.coin'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user'),
        ),
    ]
