# Generated by Django 4.2.6 on 2023-11-15 05:27

from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0002_spend_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='costBasis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.costbasis'),
        ),
        migrations.AddField(
            model_name='income',
            name='costBasis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.costbasis'),
        ),
        migrations.CreateModel(
            name='ExchangeWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitsSent', gnosis.eth.django.models.Uint256Field()),
                ('unitsReceived', gnosis.eth.django.models.Uint256Field(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('fee', gnosis.eth.django.models.Uint256Field(blank=True, null=True)),
                ('feeAUD', models.FloatField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('feeCoin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_fee', to='taxApp.coin')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
        ),
    ]
