# Generated by Django 4.2.6 on 2023-11-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0003_buy_costbasis_income_costbasis_exchangewithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
