# Generated by Django 4.2.6 on 2023-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0004_transaction_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='feeAUD',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
