# Generated by Django 4.2.6 on 2023-11-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0005_transaction_feeaud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coingecko_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=120),
        ),
    ]
