# Generated by Django 4.2.6 on 2023-11-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0006_alter_coin_coingecko_id_alter_coin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='refId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
