# Generated by Django 4.2.6 on 2023-11-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0007_buy_refid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='units',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='consumed',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='units',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='costbasis',
            name='remaining',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='costbasis',
            name='units',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True),
        ),
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='unitsReceived',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True),
        ),
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='unitsSent',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='income',
            name='units',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='sale',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='units',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='spend',
            name='units',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True),
        ),
    ]
