# Generated by Django 4.2.6 on 2023-11-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0008_alter_buy_fee_alter_buy_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='feeAUD',
            field=models.DecimalField(decimal_places=2, max_digits=79),
        ),
        migrations.AlterField(
            model_name='buy',
            name='unitPrice',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='gain',
            field=models.DecimalField(decimal_places=2, max_digits=79),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='unitPrice',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='costbasis',
            name='unitPrice',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='feeAUD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=79, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=79),
        ),
        migrations.AlterField(
            model_name='income',
            name='unitPrice',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='sale',
            name='feeAUD',
            field=models.DecimalField(decimal_places=2, max_digits=79),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unitPrice',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='spend',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=79),
        ),
        migrations.AlterField(
            model_name='spend',
            name='unitPrice',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='feeAUD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=79, null=True),
        ),
    ]
