# Generated by Django 4.2.6 on 2023-11-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0009_alter_buy_feeaud_alter_buy_unitprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='refId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
