# Generated by Django 4.2.6 on 2023-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0010_sale_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangewithdrawal',
            name='refId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
