# Generated by Django 4.2.6 on 2023-12-06 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0012_remove_spend_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='costBasis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.costbasis'),
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=18, max_digits=79)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
            ],
        ),
    ]
