# Generated by Django 4.2.6 on 2023-12-07 06:31

from django.db import migrations, models
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0013_alter_buy_costbasis_historicalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangewithdrawal',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='exchangewithdrawal',
            name='txId',
            field=gnosis.eth.django.models.HexV2Field(blank=True, null=True),
        ),
    ]
