# Generated by Django 4.2.6 on 2023-12-11 06:06

from django.db import migrations, models
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0014_exchangewithdrawal_note_exchangewithdrawal_txid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HexTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', gnosis.eth.django.models.HexV2Field()),
            ],
        ),
    ]
