# Generated by Django 4.2.6 on 2023-12-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0015_hextest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HexTest',
        ),
    ]
