# Generated by Django 4.2.6 on 2023-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0016_delete_hextest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='txId',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txHash',
            field=models.CharField(max_length=66),
        ),
    ]
