# Generated by Django 4.2.6 on 2024-02-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0017_alter_exchangewithdrawal_txid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('address', 'txHash', 'chain')},
        ),
    ]
