# Generated by Django 4.2.6 on 2024-02-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0018_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='explorerPrefix',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
