# Generated by Django 4.2.6 on 2024-02-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0019_chain_explorerprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='feeCoin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin'),
        ),
    ]
