# Generated by Django 4.2.6 on 2024-03-01 04:42

import django.core.files.storage
from django.db import migrations, models
import gnosis.eth.django.models
import taxApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0020_chain_feecoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', gnosis.eth.django.models.EthereumAddressV2Field()),
                ('abi', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/abis/', location='assets/abis'), upload_to=taxApp.models.getABIPath)),
            ],
        ),
    ]
