# Generated by Django 4.2.6 on 2024-03-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0021_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='chain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxApp.chain'),
            preserve_default=False,
        ),
    ]
