# Generated by Django 4.2.6 on 2024-03-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0022_contract_chain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='explorerPrefix',
            new_name='explorer',
        ),
    ]
