# Generated by Django 4.2.6 on 2024-03-06 02:58

from django.db import migrations
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0023_rename_explorerprefix_chain_explorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to',
            field=gnosis.eth.django.models.EthereumAddressV2Field(blank=True, max_length=128, null=True),
        ),
    ]
