# Generated by Django 4.2.6 on 2024-03-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0024_transaction_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True),
        ),
    ]
