# Generated by Django 4.2.6 on 2024-03-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0025_transaction_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
