# Generated by Django 4.2.6 on 2024-03-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0026_transaction_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitsSent', models.DecimalField(decimal_places=18, max_digits=79)),
                ('unitsReceived', models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True)),
                ('date', models.DateTimeField()),
                ('fee', models.DecimalField(blank=True, decimal_places=18, max_digits=79, null=True)),
                ('feeAUD', models.DecimalField(blank=True, decimal_places=2, max_digits=79, null=True)),
                ('refId', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
                ('txId', models.CharField(blank=True, max_length=66, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('feeCoin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_fee', to='taxApp.coin')),
                ('transactionReceive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_receive', to='taxApp.transaction')),
                ('transactionSend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_send', to='taxApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
        ),
    ]
