# Generated by Django 4.2.6 on 2024-03-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0027_tokenbridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coingecko_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tokenbridge',
            name='transactionReceive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_receive', to='taxApp.transaction'),
        ),
        migrations.AlterField(
            model_name='tokenbridge',
            name='transactionSend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_send', to='taxApp.transaction'),
        ),
    ]
