# Generated by Django 4.2.6 on 2024-03-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0029_alter_address_user_internaltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransaction',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='fromAddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internalTxFrom', to='taxApp.address'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='toAddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internalTxTo', to='taxApp.address'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction'),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='value',
            field=models.DecimalField(decimal_places=18, max_digits=79),
        ),
        migrations.CreateModel(
            name='TokenTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=18, max_digits=79)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('fromAddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenTransferFrom', to='taxApp.address')),
                ('toAddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenTransferTo', to='taxApp.address')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction')),
            ],
        ),
    ]
