# Generated by Django 4.2.6 on 2024-03-11 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0030_alter_internaltransaction_coin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fromAddr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='taxApp.address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='toAddr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='taxApp.address'),
        ),
    ]
