# Generated by Django 4.2.6 on 2024-03-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0031_transaction_fromaddr_transaction_toaddr'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('txHash', 'chain')},
        ),
    ]
