# Generated by Django 4.2.6 on 2024-03-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0032_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to',
        ),
    ]
