# Generated by Django 4.2.6 on 2024-03-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0033_remove_transaction_address_remove_transaction_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='txHash',
            new_name='hash',
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('hash', 'chain')},
        ),
    ]
