# Generated by Django 4.2.6 on 2024-03-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0034_rename_txhash_transaction_hash_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internaltransaction',
            unique_together={('transaction', 'fromAddr', 'toAddr', 'coin', 'value')},
        ),
    ]
