# Generated by Django 4.2.6 on 2024-03-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0035_alter_internaltransaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tokentransfer',
            unique_together={('transaction', 'fromAddr', 'toAddr', 'coin', 'value')},
        ),
    ]
