# Generated by Django 4.2.6 on 2024-03-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0036_alter_tokentransfer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('chain', 'address')},
        ),
    ]
