# Generated by Django 4.2.6 on 2024-03-11 08:42

from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0037_alter_token_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', gnosis.eth.django.models.EthereumAddressV2Field()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.chain')),
            ],
            options={
                'unique_together': {('chain', 'address')},
            },
        ),
        migrations.CreateModel(
            name='VaultWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=79)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.vault')),
            ],
            options={
                'unique_together': {('vault', 'transaction')},
            },
        ),
        migrations.CreateModel(
            name='VaultDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=79)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.vault')),
            ],
            options={
                'unique_together': {('vault', 'transaction')},
            },
        ),
    ]
