# Generated by Django 4.2.6 on 2024-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0039_alter_vault_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
