# Generated by Django 4.2.6 on 2024-03-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0040_alter_income_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=79)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.coin')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.income')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.vault')),
            ],
            options={
                'unique_together': {('vault', 'transaction')},
            },
        ),
    ]
