# Generated by Django 4.2.6 on 2024-03-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0041_vaultincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgtevent',
            name='costBasis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.costbasis'),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.sale'),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='spend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.spend'),
        ),
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.transaction'),
        ),
        migrations.AlterField(
            model_name='income',
            name='costBasis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.costbasis'),
        ),
        migrations.AlterField(
            model_name='vaultincome',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.income'),
        ),
    ]
