# Generated by Django 4.2.6 on 2024-03-15 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0042_alter_cgtevent_costbasis_alter_cgtevent_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.transaction'),
        ),
    ]
