# Generated by Django 4.2.6 on 2024-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0043_income_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangewithdrawal',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenbridge',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
