# Generated by Django 4.2.6 on 2024-03-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0044_exchangewithdrawal_processed_tokenbridge_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgtevent',
            name='consumed',
        ),
        migrations.RemoveField(
            model_name='cgtevent',
            name='costBasis',
        ),
        migrations.CreateModel(
            name='CGTtoCostBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed', models.DecimalField(decimal_places=18, max_digits=79)),
                ('cgtEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.cgtevent')),
                ('costBasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.costbasis')),
            ],
        ),
        migrations.AddField(
            model_name='cgtevent',
            name='costBasis',
            field=models.ManyToManyField(blank=True, through='taxApp.CGTtoCostBasis', to='taxApp.costbasis'),
        ),
    ]
