# Generated by Django 4.2.6 on 2024-03-20 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0046_alter_cgtevent_sale_alter_cgtevent_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgtevent',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.sale'),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='spend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxApp.spend'),
        ),
    ]
