# Generated by Django 4.2.6 on 2024-03-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0047_alter_cgtevent_sale_alter_cgtevent_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgtevent',
            name='discounted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cgtevent',
            name='gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=79, null=True),
        ),
    ]
