# Generated by Django 4.2.6 on 2024-03-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0048_alter_cgtevent_discounted_alter_cgtevent_gain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgtevent',
            name='discounted',
        ),
        migrations.AddField(
            model_name='cgttocostbasis',
            name='discounted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cgttocostbasis',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=79),
            preserve_default=False,
        ),
    ]
