# Generated by Django 4.2.6 on 2024-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0049_remove_cgtevent_discounted_cgttocostbasis_discounted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgtevent',
            name='method',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
