# Generated by Django 4.2.6 on 2024-05-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0050_cgtevent_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAUDTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=79)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
        ),
    ]
