# Generated by Django 4.2.6 on 2024-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0051_exchangeaudtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaudtransaction',
            name='refId',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
