# Generated by Django 4.2.6 on 2024-10-31 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0053_tokentransfer_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangewithdrawal',
            old_name='transaction',
            new_name='transactionSend',
        ),
    ]
