# Generated by Django 4.2.6 on 2024-10-31 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0054_rename_transaction_exchangewithdrawal_transactionsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangewithdrawal',
            name='transactionReceive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_receive', to='taxApp.transaction'),
        ),
        migrations.AlterField(
            model_name='exchangewithdrawal',
            name='transactionSend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_send', to='taxApp.transaction'),
        ),
    ]
