# Generated by Django 4.2.6 on 2024-11-08 00:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0055_exchangewithdrawal_transactionreceive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gain', models.DecimalField(decimal_places=2, max_digits=79)),
                ('consumed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=79)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.user')),
            ],
        ),
    ]
