# Generated by Django 4.2.6 on 2024-11-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0056_capitalgain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgttocostbasis',
            old_name='discounted',
            new_name='discountable',
        ),
    ]
