# Generated by Django 4.2.6 on 2024-11-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0057_rename_discounted_cgttocostbasis_discountable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitalgain',
            old_name='consumed',
            new_name='remaining',
        ),
    ]
