# Generated by Django 4.2.6 on 2024-11-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0058_rename_consumed_capitalgain_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgttocostbasis',
            old_name='gain',
            new_name='grossGain',
        ),
    ]
