# Generated by Django 4.2.6 on 2024-11-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0059_rename_gain_cgttocostbasis_grossgain'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgttocostbasis',
            name='netGain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=79, null=True),
        ),
        migrations.CreateModel(
            name='PriorLossConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed', models.DecimalField(decimal_places=2, max_digits=79)),
                ('capitalGain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.capitalgain')),
                ('cgtToCostBasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxApp.cgttocostbasis')),
            ],
        ),
        migrations.AddField(
            model_name='cgttocostbasis',
            name='priorLossesApplied',
            field=models.ManyToManyField(through='taxApp.PriorLossConsumption', to='taxApp.capitalgain'),
        ),
    ]
