# Generated by Django 4.2.6 on 2024-11-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxApp', '0060_cgttocostbasis_netgain_priorlossconsumption_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capitalgain',
            unique_together={('user', 'year')},
        ),
    ]
